<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <packaging>jar</packaging>
  <groupId>io.github.b12n-oss</groupId>
  <artifactId>mcp-tkx</artifactId>
  <version>2026-07-28</version>
  <name>MCP Toolkit</name>
  <description>a lib to build MCP clients and MCP servers in Clojure(script)</description>
  <inceptionYear>2025</inceptionYear>
  <licenses>
    <license>
      <name>EPL-2.0</name>
      <url>https://opensource.org/license/EPL-2.0</url>
    </license>
  </licenses>
  <scm>
    <url>https://github.com/b12n-oss/mcp-tkx</url>
    <connection>scm:git:git://github.com/b12n-oss/mcp-tkx.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/b12n-oss/mcp-tkx.git</developerConnection>
    <tag>v2025-11-25</tag>
  </scm>
  <dependencies>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure</artifactId>
      <version>1.12.5</version>
    </dependency>
    <dependency>
      <groupId>taipei.404</groupId>
      <artifactId>mate</artifactId>
      <version>0.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>tools.cli</artifactId>
      <version>1.4.256</version>
    </dependency>
    <dependency>
      <groupId>metosin</groupId>
      <artifactId>malli</artifactId>
      <version>0.20.1</version>
    </dependency>
    <dependency>
      <groupId>funcool</groupId>
      <artifactId>promesa</artifactId>
      <version>11.0.678</version>
    </dependency>
    <dependency>
      <groupId>camel-snake-kebab</groupId>
      <artifactId>camel-snake-kebab</artifactId>
      <version>0.4.3</version>
    </dependency>
  </dependencies>
  <build>
    <sourceDirectory>src</sourceDirectory>
  </build>
  <repositories>
    <repository>
      <id>clojars</id>
      <url>https://repo.clojars.org/</url>
    </repository>
  </repositories>
</project>
